---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-prd
  region: us-east-1 

availabilityZones:
  - us-east-1c
  - us-east-1d

managedNodeGroups:
  - name: ng-1
    minSize: 3
    maxSize: 5
    instanceTypes: ["t2.micro", "t3.small"]
    spot: true
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        certManager: true
        albIngress: true


