apiVersion: v1
kind: Service
metadata:
  name: ttc-app
  annotations:
    external-dns.alpha.kubernetes.io/hostname: api.herculano.xyz
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: ttc-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttc-app
spec:
  selector:
    matchLabels:
      app: ttc-app
  template:
    metadata:
      labels:
        app: ttc-app
    spec:
      containers:
      - image: 373782272813.dkr.ecr.us-east-1.amazonaws.com/ttc-app
        name: ttc-app
        ports:
        - containerPort: 80
          name: http
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: database
      - name: cloud-sql-proxy
        # It is recommended to use the latest version of the Cloud SQL proxy
        # Make sure to update on a regular schedule!
        image: gcr.io/cloudsql-docker/gce-proxy:1.17
        command:
          - "/cloud_sql_proxy"

          # If connecting from a VPC-native GKE cluster, you can use the
          # following flag to have the proxy connect over private IP
          # - "-ip_address_types=PRIVATE"

          # Replace DB_PORT with the port the proxy should listen on
          # Defaults: MySQL: 3306, Postgres: 5432, SQLServer: 1433
          - "-instances=new-project-300306:us-central1:ttc-db-prd=tcp:3306"

        # [START cloud_sql_proxy_k8s_volume_mount]
          # This flag specifies where the service account key can be found
          - "-credential_file=/secrets/service-proxy.json"
        securityContext:
          # The default Cloud SQL proxy image runs as the
          # "nonroot" user and group (uid: 65532) by default.
          runAsNonRoot: true
        volumeMounts:
        - name: sa-secret-vm
          mountPath: /secrets/
          readOnly: true
          # [END cloud_sql_proxy_k8s_volume_mount]
      # [START cloud_sql_proxy_k8s_volume_secret]
      volumes:
      - name: sa-secret-vm
        secret:
          secretName: sa-secret
      # [START cloud_sql_proxy_k8s_volume_secret]
